#App  DEV - techlab
# arquivo config de exemplo.
# função de proxy reverso direcionando para um IP
# Usando 2 ou mais  hosts em um bloco  do servidor.

#Aqui podemos ter diversaas url. Usamos a entrada x.bradesco.com na porta 80
para direfernciar o cainho que carrega o ambiente.

#O server_name dev.bradesco.com está apontando para o ambiente de dev que estar 
#nocaminho de root /var/www/html. Então quando a URL dev.bradesco.com for digitada no navegador 
#será carregado o arquivo  index.htm  que estar no caminho /var/www/html. Esse caminho pod ser /var/www/html/app-01 e assim por dianate
#Caso sua aplicação seja node.js voxcê precisa declarar a extenção logo na primeira linha do conteudo location / {}

#Nas linhas 39 e 40 66 e 67  usamos o mesmo caminho para salavar o log da sduas aplicações, mas você pode separar ou escolher 
não guarar os lohs comenatando a sduas linhas de logs

Essa configuração pode ser aplicada em um unico arquivo .conf do dominio configurado, por exemplo bradesco.com.conf

#Ambiente 01 - DEV
server {
        listen 80;
        listen [::]:80;
        #Para forçar o redirect para porta 443 descomente a linha 24
        #return 301 https://$host$request_uri;

        #URL do seu servidor registrada no seu DNS
        #Para o host responder na raiz do dominio remova o dev e adicione o wwww.bradesco.com
        server_name dev.bradesco.com;

        #Caminho do seu arquivo index ou node.js da sua aplicação
        root /var/www/html/dev;

        location /  {
        index index.html index.htm index.php;
        root /var/www/html/dev;
        try_files $uri $uri/ /index.html;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;

        }

        access_log /var/log/nginx/www.bradesco.com.access.log;
        error_log /var/log/nginx/www.www.bradesco.com.error.log;
}


#Ambiente 01 - QA
server {
        listen 80;
        listen [::]:80;

        #URL do seu servidor registrada no seu DNS
        #Para o host responder na raiz do dominio remova o qa e adicione o wwww.bradesco.com
        server_name qa.bradesco.com;;

        #Caminho do seu arquivo index ou node.js da sua aplicação
        root /var/www/html/qa;

        location /  {
        index index.html index.htm index.php;
        root /var/www/html/qa;
        try_files $uri $uri/ /index.html;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;

        }

        access_log /var/log/nginx/www.bradesco.com.access.log;
        error_log /var/log/nginx/www.www.tbradesco.com.error.log;
}

