#App  DEV - techlab
# arquivo config .confi de exemplo.
# função d eproxy reverso direcionando para um IP
# Usando apenas um 1 host virtual
server {
        listen 80;
        listen [::]:80;

        server_name ymh-dev.techlab.com;
        root /var/www/html;

        location /  {
        index index.html index.htm index.php;
        root /var/www/html;
        try_files $uri $uri/ /index.html;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;

        }

        access_log /var/log/nginx/www.techlab.com.access.log;
        error_log /var/log/nginx/www.www.techlab.com.error.log;
}
